version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
      timezone: "America/Mexico_City"
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
