ci:
    autofix_prs: false
    autoupdate_schedule: monthly
    autoupdate_commit_msg: 'chore(deps): pre-commit autoupdate'
    skip:
    -   check-dependabot

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/pre-commit
    rev: v4.3.0
    hooks:
    -   id: validate_manifest

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
    -   id: check-dependabot
    -   id: check-github-workflows
