# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TargetJsonlBlob < Formula
  desc "JSONL Singer target for local storage, S3 and Azure Blob Storage."
  homepage "https://github.com/MeltanoLabs/target-jsonl-blob"
  version "0.0.10"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/MeltanoLabs/target-jsonl-blob/releases/download/v0.0.10/target-jsonl-blob_0.0.10_darwin_amd64.tar.gz"
      sha256 "f893a5c3661c3dc644d2ad937bb745e6d19d0071032f4b31d107c795e06a6e12"

      def install
        bin.install "target-jsonl-blob"
      end
    end
    on_arm do
      url "https://github.com/MeltanoLabs/target-jsonl-blob/releases/download/v0.0.10/target-jsonl-blob_0.0.10_darwin_arm64.tar.gz"
      sha256 "8e99b0a1c239e65acffdc04d7a87ad8797f5fb05d4def21feb2a31953e816c43"

      def install
        bin.install "target-jsonl-blob"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MeltanoLabs/target-jsonl-blob/releases/download/v0.0.10/target-jsonl-blob_0.0.10_linux_amd64.tar.gz"
        sha256 "5d2a8061f72aeb3b03b08be9ee5452acc0c1f55639beb82cd828e3aa64e002de"

        def install
          bin.install "target-jsonl-blob"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MeltanoLabs/target-jsonl-blob/releases/download/v0.0.10/target-jsonl-blob_0.0.10_linux_arm64.tar.gz"
        sha256 "4591c5b35345a9ef4cf7cf4031c70cb59f8213e168c07e4b34c2ad3ae84be117"

        def install
          bin.install "target-jsonl-blob"
        end
      end
    end
  end
end
