# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TargetJsonlBlob < Formula
  desc "JSONL Singer target for local storage, S3 and Azure Blob Storage."
  homepage "https://github.com/MeltanoLabs/target-jsonl-blob"
  version "0.0.12"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/MeltanoLabs/target-jsonl-blob/releases/download/v0.0.12/target-jsonl-blob_0.0.12_darwin_amd64.tar.gz"
      sha256 "1a67e893a1096e6b0cb01ffbb3bf44f2ea4611dc811e361a5d4fcbe14c6773ea"

      def install
        bin.install "target-jsonl-blob"
      end
    end
    on_arm do
      url "https://github.com/MeltanoLabs/target-jsonl-blob/releases/download/v0.0.12/target-jsonl-blob_0.0.12_darwin_arm64.tar.gz"
      sha256 "16146c11c3528ba4bd3fa13cf7b2f7809f069b1cd4f53e4f5ac57fff01a6e821"

      def install
        bin.install "target-jsonl-blob"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MeltanoLabs/target-jsonl-blob/releases/download/v0.0.12/target-jsonl-blob_0.0.12_linux_amd64.tar.gz"
        sha256 "ef711fc37ab9f8ece2b7d9b024632e3b82399b5cf01c458f11f857c59bbfa214"

        def install
          bin.install "target-jsonl-blob"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MeltanoLabs/target-jsonl-blob/releases/download/v0.0.12/target-jsonl-blob_0.0.12_linux_arm64.tar.gz"
        sha256 "5cb14a507be1fc88f30ff2272f89a3f1118e9cc66e0df29a1cdcc587371f117a"

        def install
          bin.install "target-jsonl-blob"
        end
      end
    end
  end
end
